---
title: "ChromeQC: Library quality of linked reads"
params:
  molecules_bed:
    input: text
    label: Input BED file of molecules with columns Rname, Start, End, BX, Number_reads
    value: molecules.bed
---

```{r setup, echo=F, message=F, warning=F}
library(dplyr)
library(ggplot2)
library(knitr)
library(readr)
library(scales)
library(tibble)

knit_print.data.frame <- function(x, ...) kable(x) %>% paste(collapse = "\n") %>% asis_output
molecules_bed_filename <- params$molecules_bed
tibble(Molecules_BED = molecules_bed_filename)
```

```{r read-molecules, include=F}
read_molecules_tsv <- function(filename)
	read_tsv(
		filename,
		col_types = cols(
		  Rname = col_character(),
		  Start = col_integer(),
		  End = col_integer(),
		  BX = col_character(),
		  Reads = col_integer(),
		  MI = col_integer()
		)
	)

read_molecules_bed <- function(filename)
	read_tsv(
		filename,
		col_names = c("Rname", "Start", "End", "BX", "Reads"),
		col_types = c("ciici"))

observed_molecules <- read_molecules_bed(molecules_bed_filename) %>%
	mutate(Size = End - Start) %>%
	filter(Reads >= 4, Size >= 500)

estimated_molecules <- observed_molecules %>%
	mutate(
		Pairs = as.integer(round(Reads / 2)),
		Observed_size = End - Start,
		Size = round(Observed_size * (1 + 2 / (Pairs - 1)) - 1))

barcodes <- observed_molecules %>%
	group_by(BX) %>%
	summarize(Molecules = n(), Reads = sum(Reads), Size = sum(Size)) %>%
	arrange(desc(Reads)) %>%
	ungroup()
```

# Molecule size distribution
```{r molecule-size, echo=F}
Nx <- function(x, p) {
	sorted <- as.numeric(rev(sort(x)))
	sorted[cumsum(sorted) >= sum(sorted) * p][1]
}

N50 <- function(x) Nx(x, p = 0.5)

molecule_stats <- function(x)
	summarize(x,
		Molecules = n(),
		Barcodes = n_distinct(BX),
		N50_LPM = N50(Reads / 2),
		Weighted_mean = weighted.mean(Size, Size),
		N75 = Nx(Size, 0.75),
		N50 = Nx(Size, 0.50),
		N25 = Nx(Size, 0.25),
		Max = max(Size))

observed_stats <- molecule_stats(observed_molecules)
estimated_stats <- molecule_stats(estimated_molecules)

rbind(
	observed_stats %>% add_column(Size = "Observed", .before = 1),
	estimated_stats %>% add_column(Size = "Estimated", .before = 1))
```

# Total DNA
```{r total-dna, echo=F}
ggplot(observed_molecules) +
	aes(x = Size, weight = Size) +
	geom_histogram(binwidth = 5e3, boundary = 0) +
	scale_x_continuous(name = "Molecule size",
		labels = unit_format(unit = "kbp", scale = 1e-3)) +
	scale_y_continuous(name = "Total DNA mass",
		labels = unit_format(unit = "Mbp", scale = 1e-6)) +
	coord_cartesian(x = c(0, 250e3)) +
	ggtitle(paste0(
		"N50_Size = ", observed_stats$N50,
		", N50_LPM = ", observed_stats$N50_LPM,
		", Molecules = ", observed_stats$Molecules,
		", Barcodes = ", observed_stats$Barcodes))
```

# Molecules per barcode
```{r molecules-per-barcode, echo=F}
barcodes_summary <- barcodes %>%
	summarize(
		Molecules = sum(Molecules),
		Barcodes = n(),
		Molecules_per_barcode = Molecules / Barcodes)

ggplot(barcodes) +
	aes(x = Molecules) +
	geom_histogram(binwidth = 1) +
	labs(x = "Molecules per barcode", y = "Barcodes") +
	ggtitle(paste("Mean molecules per barcode =", barcodes_summary$Molecules_per_barcode))
```
